/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.Categoria;
import gui.Produto;

import java.sql.SQLException;
import java.text.ParseException;

import java.util.logging.Level;
import java.util.logging.Logger;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    public Main() throws SQLException {
        initComponents();
        fillCBCliente();
        fillCBFunc();
        loadRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCat = new javax.swing.JToggleButton();
        btnProduto = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCat.setText("Categoria");
        btnCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatActionPerformed(evt);
            }
        });

        btnProduto.setText("Produto");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProduto)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduto)
                    .addComponent(btnCat))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        Produto form = new Produto();
        form.setLocationRelativeTo(null);
        form.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatActionPerformed
        Categoria form = new Categoria();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_btnCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCat;
    private javax.swing.JToggleButton btnProduto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    final void fillCBCliente() throws SQLException {
//        ClienteDAO dao = new ClienteDAO();
//        List<model.Cliente> venda = dao.list();
//        jcbCliente.removeAllItems();
//        for (model.Cliente p : venda) {
//            jcbCliente.addItem(Integer.toString(p.getCpf()));
//        }
    }

    final void fillCBFunc() throws SQLException {
//        FuncionarioDAO dao = new FuncionarioDAO();
//        List<model.Funcionario> venda = dao.list();
//        jcbFunc.removeAllItems();
//        for (model.Funcionario p : venda) {
//            jcbFunc.addItem(Integer.toString(p.getCpf()));
//        }
    }

    private void loadRecords() throws SQLException {
//        String sql = "SELECT id, Valor total, Data de emissão, Funcionario_CPF, Cliente_CPF FROM Pedido, order by id;";
//
//        ResultSetTableModel tableModel = new ResultSetTableModel(sql);
//        jTable1.setModel(tableModel);
//
//        jTable1.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
//            try {
//                if (jTable1.getSelectedRow() >= 0) {
//                    Object id = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
//                    Object cliente = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1);
//                    Object filial = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2);
//                    Object funcionario = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3);
//                    String data = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4);
//
//                    txtId.setText(id.toString());
//                    txtData.setText(data.toString());
//                    jcbCliente.setSelectedItem(cliente.toString());
//                    jcbFunc.setSelectedItem(funcionario.toString());
//
//                }
//            } catch (Exception ex) {
//                System.out.println(ex.getMessage());
//            }
//        });
//
//        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
//        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
//        jTable1.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }

}
